-- Este script popula as tabelas criadas no BigQuery.
-- A cláusula VALUES é usada para inserir múltiplas linhas de uma vez.

-- Inserção de dados na tabela Clientes (sem duplicatas)
INSERT INTO `t1engenhariadados.Livraria_DevSaber_Turma3_Grupo10.clientes` (ID_Cliente, Nome_Cliente, Email_Cliente, Estado_Cliente)
VALUES
    (1, 'Thaís Falcão De Souza', 'thais.falcao@email.com', 'RJ'),
    (2, 'Ana Beatriz Torres Neri', 'ana.beatriz.costa@email.com', 'PE'),
    (3, 'Kryssia José de Mendonça', 'kryssia.j@email.com', 'SP'),
    (4, 'Denilza Lima da Silva', 'denilzal.s@email.com', 'GO'),
    (5, 'Renato Gomes', 'renato.go@email.com', 'BA'),
    (6, 'Raylane Araujo de Sousa', 'rayaraujo.s@email.com', 'RR'),
    (7, 'Denis Barbosa Soares', 'denisbarbosa.s@email.com', 'MG'),
    (8, 'Rayra Bandeira de Mello Gomes Dias', 'rayra.b@email.com', 'MG'),
    (9, 'Anelise Azevedo', 'anelise.a@email.com', 'MG'),
    (10, 'Valdemir Ferreira Júnior', 'valdemir.ferreira@email.com', 'SP'),
    (11, 'Vanessa Oliveira', 'vanessa.o@email.com', 'RJ'),
    (12, 'André Santos', 'andre.s@email.com', 'MG'),
    (13, 'Beatriz Souza', 'beatriz.s@email.com', 'SC'),
    (14, 'Rafael Lima', 'rafael.l@email.com', 'PR'),
    (15, 'Larissa Costa', 'larissa.c@email.com', 'SP'),
    (16, 'Diego Nascimento', 'diego.n@email.com', 'RJ'),
    (17, 'Patrícia Mendes', 'patricia.m@email.com', 'PE'),
    (18, 'Eduardo Almeida', 'eduardo.a@email.com', 'BA'),
    (19, 'Fernanda Barbosa', 'fernanda.b@email.com', 'SP'),
    (20, 'Guilherme Pinto', 'guilherme.p@email.com', 'MG'),
    (21, 'Isabela Cardoso', 'isabela.c@email.com', 'SP'),
    (22, 'Rodrigo Teixeira', 'rodrigo.t@email.com', 'RJ'),
    (23, 'Aline Pires', 'aline.p@email.com', 'RS'),
    (24, 'Marcelo Dias', 'marcelo.d@email.com', 'SP'),
    (25, 'Carolina Duarte', 'carolina.d@email.com', 'BA'),
    (26, 'Vinícius Moreira', 'vinicius.m@email.com', 'SP'),
    (27, 'Priscila Ramos', 'priscila.r@email.com', 'RJ'),
    (28, 'Alexandre Castro', 'alexandre.c@email.com', 'PR'),
    (29, 'Letícia Ribeiro', 'leticia.r@email.com', 'SP'),
    (30, 'Mateus Correia', 'mateus.c@email.com', 'MG'),
    (31, 'Bianca Fonseca', 'bianca.f@email.com', 'SC'),
    (32, 'Leonardo Moraes', 'leonardo.m@email.com', 'SP'),
    (33, 'Tatiane Monteiro', 'tatiane.m@email.com', 'RJ'),
    (34, 'Samuel Carvalho', 'samuel.c@email.com', 'BA'),
    (35, 'Débora Antunes', 'debora.a@email.com', 'PE'),
    (36, 'Igor Figueiredo', 'igor.f@email.com', 'SP'),
    (37, 'Paula Brito', 'paula.b@email.com', 'RJ'),
    (38, 'Vitor Mendes', 'vitor.m@email.com', 'SP'),
    (39, 'Rafaela Azevedo', 'rafaela.a@email.com', 'MG'),
    (40, 'Célio Batista', 'celio.b@email.com', 'SP'),
    (41, 'Talita Cunha', 'talita.c@email.com', 'RS'),
    (42, 'Otávio Freitas', 'otavio.f@email.com', 'RJ'),
    (43, 'Mônica Carvalho', 'monica.c@email.com', 'SP'),
    (44, 'Sérgio Matos', 'sergio.m@email.com', 'BA'),
    (45, 'Mariana Alves', 'mariana.alves@email.com', 'SP'),
    (46, 'Pedro Henrique', 'pedro.h@email.com', 'RJ'),
    (47, 'Juliana Rocha', 'juliana.r@email.com', 'MG'),
    (48, 'Felipe Martins', 'felipe.m@email.com', 'RS'),
    (49, 'Camila Ferreira', 'camila.f@email.com', 'BA'),
    (50, 'Thiago Gomes', 'thiago.g@email.com', 'SP');